### ISSUE TITLE
[FEATURE] Arm Build Support

### ISSUE THREAD

**Issue by Sussy-OS** [Open-Typer/Open-Typer#39]
**Is your feature request related to a problem? Please describe.**
Good percentage of Linux users use Arm, so Arm builds would make sense for Open-Typer.

**Describe the solution you'd like**
For Arm builds to be made.

**Comment by adazem009** [comment]
Open-Typer already supports arm64 and armhf snap packages, but we need arm64 and armhf AppImages.
